# Production - Environment Variable Based
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Actuator - health endpoint only
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

# Elasticsearch
spring.data.elasticsearch.repositories.enabled=true
spring.elasticsearch.uris=${ES_URL}
spring.elasticsearch.username=${ES_USERNAME:}
spring.elasticsearch.password=${ES_PASSWORD:}
