spring.application.name=aidom-backend
server.port=8090

spring.mvc.problem-details.enabled=true

# Common Auth Defaults
app.auth.jwt.access-token-validity=30m
app.auth.jwt.refresh-token-validity=14d
app.auth.jwt.auth-code-validity=60s
app.auth.oauth2.default-success-uri=http://localhost:3000/auth/callback
app.auth.oauth2.authorized-redirect-uris=http://localhost:3000/auth/callback
app.auth.cors.allowed-origins=http://localhost:3000